---
title: "Problem Set 5"
format: html
---


1
30538 Problem Set 5: Web Scraping
Peter Ganong, Maggie Shi, Akbar Saputra, and Will Pennington
2024-11-03
Due 11/9 at 5:00PM Central. Worth 100 points + 10 points extra credit.
Submission Steps (10 pts)


1. This problem set is a paired problem set.
2. Play paper, scissors, rock to determine who goes first. Call that person Partner 1.
• Partner 1 (Daniel Avila, davila2020):
• Partner 2 (Nasser Alshaya, alshaya):



3. Partner 1 will accept the ps5 and then share the link it creates with their partner. You
can only share it with one partner so you will not be able to change it after your partner
has accepted.
4. “This submission is our work alone and complies with the 30538 integrity policy.” Add
your initials to indicate your agreement: **DA** **NA**



5. “I have uploaded the names of anyone else other than my partner and I worked with on
the problem set here” (1 point)
6. Late coins used this pset: **0** Late coins left after submission: **2**
7. Knit your ps5.qmd to an PDF file to make ps5.pdf,
• The PDF should not be more than 25 pages. Use head() and re-size figures when
appropriate.
8. (Partner 1): push ps5.qmd and ps5.pdf to your github repo.
9. (Partner 1): submit ps5.pdf via Gradescope. Add your partner on Gradescope.
10. (Partner 1): tag your submission in Gradescope

```{python}
import pandas as pd
import altair as alt
import time
import requests
from bs4 import BeautifulSoup

import warnings 
warnings.filterwarnings('ignore')
alt.renderers.enable("png")

url = "https://oig.hhs.gov/fraud/enforcement/"
response = requests.get(url)
soup = BeautifulSoup(response.text, 'lxml')
soup.text[0:50]
```


1     (30 points) Step 1: Develop initial scraper and crawler

1. (Partner 1) Scraping: Go to the first page of the HHS OIG’s “Enforcement Actions”
page and scrape and collect the following into a dataset:
• Title of the enforcement action
• Date
• Category (e.g, “Criminal and Civil Actions”)
• Link associated with the enforcement action
Collect your output into a tidy dataframe and print its head.

```{python}
tag = soup.find_all("ul")
ul_children = soup.find_all(lambda t: t.name == 'ul' and t.find_all("div"))

# title of enforcement action
ul_children_titles = soup.find_all(lambda t: t.name == 'ul' and t.find_all("a"))

titles_list = []
for title in ul_children_titles:
    for a in title.find_all("a"):
        text = a.get_text()
        titles_list.append(text)

     ## selecting only the titles, since the previous version of titles_list has extra text
titles_list = titles_list[136:156]

# date
ul_children_date = soup.find_all(lambda t: t.name == 'div' and t.find_all("span"))

dates_list = []
for date in ul_children_date:
    for span in date.find_all("span"):
        date = span.get_text()
        dates_list.append(date)

dates_list = dates_list[33:53]


# category
ul_children_category = soup.find_all(lambda t: t.name == 'ul' and t.find_all("span") and t.find_all("li"))

category_list = []
for category in ul_children_category:
    for li in category.find_all("li"):
        category = li.get_text("")
        category_list.append(category)

for i in range(len(category_list)):
    category_list[i] = category_list[i].replace("\n","")

category_list = category_list[74:135]

string_check = ["Criminal and Civil Actions", "State Enforcement Agencies"]

category_list_new = []
for i in range(len(category_list)):
    if category_list[i] == string_check[0] or category_list[i] == string_check[1]:
        category_list_new.append(category_list[i])
    else:
        pass

#links
links_list = []
for item in ul_children:
    for a in item.find_all('a'):
        links_list.append(a["href"])

df = pd.DataFrame({
    "ea_titles": titles_list,
    "dates": dates_list,
    "categories": category_list_new,
    "links": links_list})

df.head()
```


2. (Partner 1) Crawling: Then for each enforcement action, click the link and collect
the name of the agency involved (e.g., for this link, it would be U.S. Attorney’s Oﬀice,
Eastern District of Washington).
Update your dataframe with the name of the agency and print its head.
Hint: if you go to James A. Robinson’s profile page at the Nobel Prize website here, right-
click anywhere along the line “Aﬀiliation at the time of the award: University of Chicago,
Chicago, IL, USA”, and select Inspect, you’ll see that this aﬀiliation information is located at
the third <p> tag out of five <p> tags under the <div class="content">. Think about how
you can select the third element of <p> out of five <p> elements so you’re sure you scrape the
aﬀiliation information, not other. This way, you can scrape the name of agency to answer this
question.


2      (30 points) Making the scraper dynamic

1. Turning the scraper into a function: You will write a function that takes as input
a month and a year, and then pulls and formats the enforcement actions like in Step 1
starting from that month+year to today.

• This function should first check that the year inputted >= 2013 before starting to
scrape. If the year inputted < 2013, it should print a statement reminding the user
to restrict to year >= 2013, since only enforcement actions after 2013 are listed.

• It should save the dataframe output into a .csv file named as “enforcement_actions_
year_month.csv” (do not commit this file to git)

• If you’re crawling multiple pages, always add 1 second wait before going to the next
page to prevent potential server-side block. To implement this in Python, you may
look up .sleep() function from time library.

a. (Partner 2) Before writing out your function, write down pseudo-code of the steps that
your function will go through. If you use a loop, discuss what kind of loop you will use
and how you will define it.

```
1. Define a function which takes two inpust: year, month
2. Inside the function specify an if condition, if less than 2013 print message and return empty.
3. Create two datetime objects for start and end times.
4. Assign the url to a string, create a response object and use it to create a soup object.
5. Create an empty list for all_actions, assign current_date to start_date.
6. Using a for loop, iterate over the list of actions using soup objects with tag "ul" and class "usa-card-group padding-y-0".
7. Iterate over elements inside list of actions using soup objects with tag "li" and class "usa-card card--list pep-card--minimal mobile:grid-col-12"
8. Assign content to be extracted as the following:
    title: ul_children_titles = soup.find_all(lambda t: t.name == 'ul' and t.find_all("a"))
    date: ul_children_date = soup.find_all(lambda t: t.name == 'div' and t.find_all("span")).
    category:ul_children_category = soup.find_all(lambda t: t.name == 'ul' and t.find_all("span") and t.find_all("li"))
    link:

```

b. (Partner 2) Now code up your dynamic scraper and run it to start collecting the enforce-
ment actions since January 2023. How many enforcement actions do you get in your final
dataframe? What is the date and details of the earliest enforcement action it scraped?

```{python}
import datetime
def scrape_hhs_oig(year, month):
    """
    Scrapes the HHS OIG's Enforcement Actions page for a given year and month.

    Args:
        year (int): The year to filter by.
        month (int): The month to filter by.

    Returns:
        list: A dataframe containing the scraped data.
    """
    url = "https://oig.hhs.gov/fraud/enforcement/"
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'lxml')
    start_date = datetime.datetime(year, month, 1)
    if year < 2013:
        print("Please input a year greater than or equal to 2013.")
        return
    enforcements =[]
    # Iterate over each item under ul
    for li in soup.find_all('li', class_='usa-card'):
        item = {}
        # Extract title and link
        h2 = li.find('h2', class_='usa-card__heading')
        a_tag = h2.find('a', href=True)
        item['title'] = a_tag.get_text(strip=True)
        item['link'] = a_tag['href']
        # Extract date and category
        date_span = li.find('span', class_='text-base-dark')
        item['date'] = date_span.get_text(strip=True)
        
        category_li = li.find('ul', 
        class_ = 'display-inline add-list-reset')
        item['category'] = category_li.get_text(strip=True)

        # Append item to data list if it has content
        enforcements.append(item)
    '''
    # Crawling:
    for i in range(41):
        link = f'https://oig.hhs.gov/fraud/enforcement/?page={i}'
        response = requests.get(link)
        soup = BeautifulSoup(response.text, 'lxml')
        for li in soup.find_all('li', class_='usa-card'):
        # Extract title and link
            h2 = li.find('h2', class_='usa-card__heading')
            a_tag = h2.find('a', href=True)
            item['title'] = a_tag.get_text(strip=True)
            item['link'] = a_tag['href']
            # Extract date and category
            date_span = li.find('span', class_='text-base-dark')
            item['date'] = date_span.get_text(strip=True)
            
            category_li = li.find(lambda t: t.name == 'header' and t.find('div') and t.find('span') and t.find('ul'))
            item['category'] = category_li.get_text(strip=True)
            print(link)
        # Add a 1-second delay between requests
        time.sleep(1)
    '''
    # Creating dataframe of enforcements:
    df_enforcements = pd.DataFrame(enforcements)

    df_enforcements["date"] = pd.to_datetime(
        df_enforcements["date"])
    df_enforcements = df_enforcements[(df_enforcements["date"]
    >= start_date) & 
    (df_enforcements["date"] <= datetime.datetime.now())]

    return df_enforcements
```

```{python}
import datetime
def scrape_hhs_oig(year, month):
    """
    Scrapes the HHS OIG's Enforcement Actions page for a given year and month.

    Args:
        year (int): The year to filter by.
        month (int): The month to filter by.

    Returns:
        list: A dataframe containing the scraped data.
    """
    start_date = datetime.datetime(year, month, 1)
    if year < 2013:
        print("Please input a year greater than or equal to 2013.")
        return
    enforcements =[]
    # Crawling:
    for i in range(41):
        link = f'https://oig.hhs.gov/fraud/enforcement/?page={i}'
        response = requests.get(link)
        soup = BeautifulSoup(response.text, 'lxml')
        
        for li in soup.find_all('li', class_='usa-card'):
            item = {}
        # Extract title and link
            h2 = li.find('h2', class_='usa-card__heading')
            a_tag = h2.find('a', href=True)
            item['title'] = a_tag.get_text(strip=True)
            item['link'] = a_tag['href']
            # Extract date and category
            date_span = li.find('span', class_='text-base-dark')
            if date_span:  # Check if date_span is not None
                item['date'] = date_span.get_text(strip=True)

            category_li = li.find('ul',
             class_ = 'display-inline add-list-reset')
            item['category'] = category_li.get_text(strip=True)
            enforcements.append(item)
        print(link)
        # Add a 1-second delay between requests
        time.sleep(1)
    # Creating dataframe of enforcements:
    df_enforcements = pd.DataFrame(enforcements)
    print(len(df_enforcements))
    df_enforcements['date'] = pd.to_datetime(df_enforcements['date'])
    df_enforcements = df_enforcements[(df_enforcements['date'] >= start_date) & (df_enforcements['date'] <= datetime.datetime.now())]
    df_enforcements.to_csv('enforcement_actions_year_month.csv',
    index = False)
    return df_enforcements

```

```{python}
df_test = scrape_hhs_oig(2023, 11)
```

```{python}
page = soup.find('a', class_='pagination__link')
page_url = page['href']
page_url = ("https://oig.hhs.gov/fraud/enforcement/" + 
page_url)
page_url
```

```{python}
test =[]

# Iterate over each list item under ul
for li in soup.find_all('li', class_='usa-card'):
    item = {}

    # Extract title and link
    h2 = li.find('h2', class_='usa-card__heading')
    a_tag = h2.find('a', href=True)
    if a_tag:
        item['title'] = a_tag.get_text(strip=True)
        item['link'] = a_tag['href']
    
    # Extract date and category
    date_span = li.find('span', class_='text-base-dark')
    item['date'] = date_span.get_text(strip=True)
    
    category_li = li.find(lambda t: t.name == 'header' and t.find('div') and t.find('span') and t.find('ul'))
    item['category'] = category_li.get_text(strip=True)

    # Append item to data list if it has content:
    test.append(item)

```

c. (Partner 1) Now, let’s go a little further back. Test your partner’s code by collecting
the actions since January 2021. Note that this can take a while. How many enforcement
actions do you get in your final dataframe? What is the date and details of the earliest
enforcement action it scraped? Use the dataframe from this process for every question
after this.
Hint:
a. If you go to the next page in this HHS OIG’s “Enforcement Actions” page, you’ll notice
a pattern:
• Second page URL: https://oig.hhs.gov/fraud/enforcement/?page=2
• Third page URL: https://oig.hhs.gov/fraud/enforcement/?page=3
• and so on ...
b. Write a pseudo-code to help you think about how to make the crawler dynamic. You
need to loop through all the pages in the website. Hint: Note that a simple for loop
may not be suﬀicient for what this crawler requires. Use online resources to look into
different types of loops or different ways of using for loops to see if there is something
that is more appropriate for this task.


3       (15 points) Plot data based on scraped data (using altair)

1. (Partner 2) Plot a line chart that shows: the number of enforcement actions over
time (aggregated to each month+year) overall since January 2021.

2. (Partner 1) Plot a line chart that shows: the number of enforcement actions split
out by:
• “Criminal and Civil Actions” vs. “State Enforcement Agencies”
• Five topics in the “Criminal and Civil Actions” category: “Health Care Fraud”,
“Financial Fraud”, “Drug Enforcement”, “Bribery/Corruption”, and “Other”. Hint:
You will need to divide the five topics manually by looking at the title and assigning
the relevant topic. For example, if you find the word “bank” or “financial” in the
title of an action, then that action should probably belong to “Financial Fraud”
topic.

4:         (15 points) Create maps of enforcement activity
For these questions, use this US Attorney District shapefile (link) and a Census state shapefile
(link)

1. (Partner 1) Map by state: Among actions taken by state-level agencies, clean the state
names you collected and plot a choropleth of the number of enforcement actions for each
state. Hint: look for “State of” in the agency info!

2. (Partner 2) Map by district: Among actions taken by US Attorney District-level agen-
cies, clean the district names so that you can merge them with the shapefile, and then
plot a choropleth of the number of enforcement actions in each US Attorney District.
Hint: look for “District” in the agency info.


(10 points) Extra credit: Calculate the enforcement actions on a per-capita basis
(Both partners can work together)

1. Use the zip code shapefile from the previous problem set and merge it with zip code-
level population data. (Go to Census Data Portal, select “ZIP Code Tabulation Area”,
check “All 5-digit ZIP Code Tabulation Areas within United States”, and under “P1
TOTAL POPULATION” select “2020: DEC Demographic and Housing Characteristics”.
Download the csv.).

2. Conduct a spatial join between zip code shapefile and the district shapefile, then aggre-
gate to get population in each district.

3. Map the ratio of enforcement actions in each US Attorney District. You can calculate the
ratio by aggregating the number of enforcement actions since January 2021 per district,
and dividing it with the population data.


